In [5]:
import numpy as np
import pandas as pd

In [65]:
import os
path_root=os.getcwd()

In [27]:
df=pd.read_csv("../00_datasets/play_tennis.csv")
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [12]:
given=['Sunny','Mild',"Normal","Strong"] ## what is the decision ? play or not play.

In [62]:
## counting
n_total=df.shape[0]

given_yes=df[df['play']=="Yes"]
given_no=df[df["play"]=='No']

n_of_yes=given_yes.shape[0]
n_of_no=given_no.shape[0]

p_yes=n_of_yes/n_total
p_no=n_of_no/ n_total
print(n_of_yes)
print(n_of_no)
print(p_yes)
print(p_no)

9
5
0.6428571428571429
0.35714285714285715

# Likelihood calculation for play="Yes"

In [29]:
given_yes

    day   outlook  temp humidity    wind play
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
6    D7  Overcast  Cool   Normal  Strong  Yes
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes

In [52]:
given_no

    day outlook  temp humidity    wind play
0    D1   Sunny   Hot     High    Weak   No
1    D2   Sunny   Hot     High  Strong   No
5    D6    Rain  Cool   Normal  Strong   No
7    D8   Sunny  Mild     High    Weak   No
13  D14    Rain  Mild     High  Strong   No

In [56]:
given_no

    day outlook  temp humidity    wind play
0    D1   Sunny   Hot     High    Weak   No
1    D2   Sunny   Hot     High  Strong   No
5    D6    Rain  Cool   Normal  Strong   No
7    D8   Sunny  Mild     High    Weak   No
13  D14    Rain  Mild     High  Strong   No

## probability calculation for 'outlook'

In [58]:
n_of_overcast_when_yes=given_yes[given_yes['outlook']=="Overcast"].shape[0]
n_of_sunny_when_yes=given_yes[given_yes['outlook']=="Sunny"].shape[0]
n_of_rain_when_yes=given_yes[given_yes['outlook']=="Rain"].shape[0]


p_outlook_overcast_given_yes= n_of_overcast_when_yes / n_of_yes# P(outlook=overcase | yes)
p_outlook_rain_given_yes= n_of_rain_when_yes / n_of_yes# P(outlook=rain | yes)
p_outlook_sunny_given_yes= n_of_sunny_when_yes / n_of_yes# P(outlook=sunny | yes)
p_yes=n_of_yes/ n_total


## outlook when play='No'

n_of_overcast_when_no=given_no[given_no['outlook']=="Overcast"].shape[0]
n_of_sunny_when_no=given_no[given_no['outlook']=="Sunny"].shape[0]
n_of_rain_when_no=given_no[given_no['outlook']=="Rain"].shape[0]


p_outlook_overcast_given_no= n_of_overcast_when_no / n_of_no# P(outlook=overcase | yes)
p_outlook_rain_given_no= n_of_rain_when_no / n_of_no# P(outlook=rain | yes)
p_outlook_sunny_given_no= n_of_sunny_when_no / n_of_no# P(outlook=sunny | yes)
p_yes=n_of_no/ n_total

print(p_outlook_overcast_given_yes)
print(p_outlook_rain_given_yes)
print(p_outlook_sunny_given_yes)
print(p_outlook_overcast_given_no)
print(p_outlook_rain_given_no)
print(p_outlook_sunny_given_no)

0.4444444444444444
0.3333333333333333
0.2222222222222222
0.0
0.4
0.6

In [39]:
print(p_yes)

0.6428571428571429

## probability calculation for `temp`

In [41]:
given_yes

    day   outlook  temp humidity    wind play
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
6    D7  Overcast  Cool   Normal  Strong  Yes
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes

In [59]:
n_of_hot_when_yes=given_yes[given_yes["temp"]=='Hot'].shape[0]
n_of_mild_when_yes=given_yes[given_yes['temp']=="Mild"].shape[0]
n_of_cool_when_yes=given_yes[given_yes["temp"]=="Cool"].shape[0]

p_of_temp_hot_when_yes=n_of_hot_when_yes / n_of_yes # p(temp="Hot" | yes)
p_of_temp_mild_when_yes=n_of_mild_when_yes/ n_of_yes
p_of_temp_cool_when_yes=n_of_cool_when_yes / n_of_yes



n_of_hot_when_no=given_no[given_no["temp"]=='Hot'].shape[0]
n_of_mild_when_no=given_no[given_no['temp']=="Mild"].shape[0]
n_of_cool_when_no=given_no[given_no["temp"]=="Cool"].shape[0]

p_of_temp_hot_when_no=n_of_hot_when_no / n_of_no # p(temp="Hot" | yes)
p_of_temp_mild_when_no=n_of_mild_when_no/ n_of_no
p_of_temp_cool_when_no=n_of_cool_when_no / n_of_no

print(p_of_temp_hot_when_yes)
print(p_of_temp_mild_when_yes)
print(p_of_temp_cool_when_yes)

print(p_of_temp_hot_when_no)
print(p_of_temp_mild_when_no)
print(p_of_temp_cool_when_no)

0.2222222222222222
0.4444444444444444
0.3333333333333333
0.4
0.4
0.2

## humidity when play="Yes"

In [60]:
n_of_normal_when_yes=given_yes[given_yes["humidity"]=="Normal"].shape[0]
n_of_high_when_yes=given_yes[given_yes["humidity"]=="High"].shape[0]
p_of_humidity_normal_when_yes=n_of_normal_when_yes/ n_of_yes # p(humidity=Normal | Yes)
p_of_humidity_high_when_yes=n_of_high_when_yes / n_of_yes

n_of_normal_when_no=given_no[given_no["humidity"]=="Normal"].shape[0]
n_of_high_when_no=given_no[given_no["humidity"]=="High"].shape[0]
p_of_humidity_normal_when_no=n_of_normal_when_no/ n_of_no # p(humidity=Normal | No)
p_of_humidity_high_when_no=n_of_high_when_no / n_of_no

print(p_of_humidity_normal_when_yes)
print(p_of_humidity_high_when_yes)
print(p_of_humidity_normal_when_no)
print(p_of_humidity_high_when_no)

0.6666666666666666
0.3333333333333333
0.2
0.8

## wind when play="Yes"

In [47]:
given_yes["wind"]

2       Weak
3       Weak
4       Weak
6     Strong
8       Weak
9       Weak
10    Strong
11    Strong
12      Weak
Name: wind, dtype: str

In [61]:
n_of_weak_when_yes=given_yes[given_yes["wind"]=="Weak"].shape[0]
n_of_strong_when_yes=given_yes[given_yes["wind"]=="Strong"].shape[0]
p_of_wind_weak_when_yes=n_of_weak_when_yes / n_of_yes
p_of_wind_strong_when_yes= n_of_strong_when_yes /n_of_yes


n_of_weak_when_no=given_no[given_no["wind"]=="Weak"].shape[0]
n_of_strong_when_no=given_no[given_no["wind"]=="Strong"].shape[0]
p_of_wind_weak_when_no=n_of_weak_when_no / n_of_no
p_of_wind_strong_when_no= n_of_strong_when_no /n_of_no

print(p_of_wind_weak_when_yes)
print(p_of_wind_strong_when_yes)
print(p_of_wind_weak_when_no)
print(p_of_wind_strong_when_no)

0.6666666666666666
0.3333333333333333
0.4
0.6

In [63]:
# p(yes | sunny, mild, normal, strong)= p(sunny, mild, normal , strong | yes)*p(yes)
# P(outlook=sunny|yes)*p(temp=mild|yes)*p(humidity=normal|yes)*p(wind=strong |yes)
posterior_yes=p_yes * p_outlook_sunny_given_yes * p_of_temp_mild_when_yes * p_of_humidity_normal_when_yes * p_of_wind_strong_when_yes
posterior_no=p_no * p_outlook_sunny_given_no * p_of_temp_mild_when_no * p_of_humidity_normal_when_no * p_of_wind_strong_when_no

In [64]:
print(posterior_yes)
print(posterior_no)

0.014109347442680775
0.010285714285714285

### since, `posterior_yes > posterior_no`, so `play="yes"` is predicted